j4ck_passwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65356537353835353363353936653437303631623638383934376132393335623230633334643931
          3463366632313337393764366263323161343366323233360a663239633935393233633962306330
          36363737643133346134363933383633343234333232323561336434623163366164363835313839
          3035393035613632310a363464356636626134646365356434383334363466343138613031316639
          33373234633630623166643337333830643463623330333230666132326636623464626265306661
          38643336356364366537373461316563306535643238383363323235313134366363646137666666
          37626331353038396364393430663136633831316138326365646634353938633832336466623466
          63366566396239333565303233306632656432636631613137623936396662616437376137366137
          34303961353764343066386364356136623431333062613163326538356132636561

elizabeth_passwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35366635313937643230663065326436336332653039666262663064626566653362363363353563
          3639386232373839363662636532343564396530393832610a336239623364346130663638623965
          66346434326234633263356537396563323363343764653131343731643866363632373365633934
          3031336330313363330a656336336331373433303037353062663963353236653638643238363863
          34626562643562336433346263376534356335373562643131336435353664356135383564336463
          31636230383463326664633962333362366537643333356634653135373036353438336562663630
          39623533356266343961613965633964313436613731346464383531363363386665613633633236
          36333065313133396534633631393265343430313539636438366235643431653632363162386265
          61356534303337663838613565666364613538316663333033633430623633336161
